const MovieData =[
    {
    id:Math.random(),
    title:"coco",
    descrption:"Coco is a 3D computer-engineered comic animated movie released in 2017, produced by Pixar Studios and distributed by The Walt Disney Film Company, and co-directed by Lee Edward Enrich and Adrian Molina.",
    posterUrl:"https://www.aleqt.com/sites/default/files/styles/scale_660/public/rbitem/2017/12/28/746911-391835485.jpg",
    rate:"4",
    trailerUrl:"https://www.youtube.com/embed/yg8116aeD7E",
    },
    {
        id:Math.random(),
        title:"Mr Fox",
        descrption:"It is an American stop-motion animation film directed by Wes Anderson, who co-wrote the script with screenwriter Noah Bumpach and produced by Regency Enterprises, Indian Pant Brush, and Twentieth Century Fox. The film was released in the United States on November 13.",
        posterUrl:"https://i.ytimg.com/vi/B-J95eYpYZM/movieposter.jpg",
        rate:"3",
        trailerUrl:"https://www.youtube.com/embed/K_BzxFkkImI",
    },
    {
        id:Math.random(),
        title:"Moana",
        descrption:"Moana, a Maori word meaning ocean, is a 3D animated lyrical and fantasy adventure comic American film, and is the 56th film in the Walt Disney Company Animated series of feature films released by the Walt Disney Animation Studios.",
        posterUrl:"https://www.arthipo.com/image/cache/catalog/poster/movie/759-1554/pfilm1042-moana-26hwy6-film-movie-posters-cinema-kanvas-tablo-canvas-1000x1000.jpg",
        rate:"2",
        trailerUrl:"https://1.bp.blogspot.com/-CKqm3mG_2Nc/XsR1rAtSZ3I/AAAAAAAAB1Q/2ddoEoD5cXkyaZ4GDU2i7d_cXDIfZ8InQCLcBGAsYHQ/s400/r_moana_header_poststreet_mobile_bd574a31.webp",
    },
    {
        id:Math.random(),
        title:"the Emperor's New Groove",
        descrption:"The Emperor's New Life is an animated film by The Walt Disney Company. The film is a humorous genre, focusing on the extent of vanity, racism and selfishness practiced by some, without regard for the other.",
        posterUrl:"https://lumiere-a.akamaihd.net/v1/images/open-uri20150422-12561-lxwsqg_513005ba.jpeg",
        rate:"5",
        trailerUrl:"https://www.youtube.com/embed/cPAbx5kgCJo",
    },
    {
        id:Math.random(),
        title:"Scoop",
        descrption:"The latest installment in the mysterious gangster franchise reinforces the one universal truth, that Scooby-Doo never gets old. Please pull out the snacks and dive into the next gang adventure. Investigate a plot to release the evil dog Cerberus. And on their way, they discover. ",
        posterUrl:"https://kidstoon.net/wp-content/uploads/2020/05/SCOOB-2020.jpg",
        rate:"1",
        trailerUrl:"https://www.youtube.com/embed/tBpocXwxPeI",
    },
    {
        id:Math.random(),
        title:"The Willoughbys",
        descrption:"Based on Lewis Lowry's book, “The Willoughbys” tells the story of four siblings who decide they would be better off raising themselves. After their parents go on vacation without the kids, the siblings start their own adventure. Fedoron via high-speed car chases, flying spaceships, and candy factories. All in search of the family they always dreamed of.",
        posterUrl:"https://upload.wikimedia.org/wikipedia/en/a/a0/The_Willoughbys_Theatrical_release_poster.jpg",
        rate:"5",
        trailerUrl:"https://www.youtube.com/embed/HnG4ag3Nkes",
    },
    {
        id:Math.random(),
        title:"Frozen",
        descrption:"Disney’s Frozen” is now streamed for everyone to watch and sing along with. Anna, Elsa, Kristoff, Olaf and Sven enter an enchanted forest in search of ancient secrets and frightening sounds. Once again they have to face the fact that in order to save “Arendelle”, they risk losing each other. The supplementary segment also features some distinct melodies, including “Into the Unknown” and “Reindeer Are Better than People”.",
        posterUrl:"https://upload.wikimedia.org/wikipedia/en/4/4f/Frozen_2_poster.jpg",
        rate:"5",
        trailerUrl:"https://www.youtube.com/embed/L0MK7qz13bU",
    },
];
export default MovieData;